### ISSUE TITLE
Add Example Configuration files

### ISSUE THREAD

**Issue by alexekuo** [kria/TfsNotificationRelay#25]
Add config examples that start at bare minimum along with full featured examples

**Comment by kria** [comment]
I guess it's not the most user-friendly piece of software, but there are some examples in the [config][0] and [wiki][1]. Anything in particular you want explained more thoroughly?

[0]: https://github.com/kria/TfsNotificationRelay/blob/master/TfsNotificationRelay/app.config
[1]: https://github.com/kria/TfsNotificationRelay/wiki

**Comment by humamaki** [comment]
Hello Kria,
On the event rules can you clarify which fields are required and which fields are optional. I'm not sure if leaving some of the fields empty will cause issues or not.

Thank you.

**Comment by kria** [comment]
Since the latest version ([1.15.0](https://github.com/kria/TfsNotificationRelay/releases/tag/v1.15.0)), all arguments except `notify`are optional. So this is a valid rule that will let everything through:
```
<rule notify="true" />
```
For instance, a missing `teamProject` or `teamProject=""` means that notifications will be relayed for all projects.

Some filter only apply to specific events so if you have set `gitBranch="develop"`, that doesn't affect whether or not a `WorkItemChanged`notification is relayed. Take a look [here](https://github.com/kria/TfsNotificationRelay/wiki/Events-and-filters) to see which filters affect which events.

**Comment by humamaki** [comment]
Thank you very much for your quick response. I really appreciate your help.
What about this :

<userMap id="slackusers">
        <add tfsUser="MYDOMAIN\kria" mappedUser="UXXXXXXXX" />
</userMap>

Is this the login to TFS?

Thank you again.

**Comment by kria** [comment]
This is a list of one or many users. `tfsUser` is the account that people use to login to TFS, but it's not necessary for TfsNotificationRelay to work.

`userMap` a way to connect Windows users to their corresponding external user. The point of doing that is that if you want to send a direct message to someone or generate a highlighted notification on the external system, you need to know their username or id on that system. The usermap is connected to a bot using the `userMapId` argument.

This mechanism is used by the DirectMessageNotifier to send direct messages to Slack and by the [mapped*User parameters](https://github.com/kria/TfsNotificationRelay/wiki/Notification-formatting).

In this screenshot, it's used to generate a highlight and sound in Slack:

![image](https://cloud.githubusercontent.com/assets/144572/13207655/03762008-d911-11e5-959d-3c7289f0545c.png)

**Comment by humamaki** [comment]
Thank you very much. It is working now and I really appreciate your help.
