### ISSUE TITLE
Team Support

### ISSUE THREAD

**Issue by gregpakes** [kria/TfsNotificationRelay#9]
I have forked and am starting to implement Team Support.  The scenario is that we have different teams within our TFS and we have matching team slack channels.  So I only want checkins from team members in Team A to go to the Team A slack channel.

I have basically finished it, but wanted to open this issue up to open discussion.

**Comment by kria** [comment]
Sounds like a great addition! Send a PR and I'll take a look at it.

**Comment by thesoftwarejedi** [comment]
I'm interested in this as well.  We could probably implement that for our frontend/backend devs.

**Comment by gregpakes** [comment]
I have this working for the Checkin handler.  In my case, it doesn't really make sense on any of the other handlers, however it feels a bit strange having it just on the Checkin handler.

What are your thoughts?

**Comment by kria** [comment]
How have you done it? I imagined you'd add a new rule attribute and modify the IsMatch method on the notification. It's a bit strange since I only have one type of rule element, but a team parameter is certainly more generally applicable than buildDefinition is :)

I think a team criterion could be useful for more events, but I can implement it for those if you do it for Checkin.

**Comment by shaneedwards** [comment]
I just started implementing the TfsNotifier today and ran into this same limitation.  We run all of our projects under one parent TFS Project and then use area paths and teams to separate out the work.  (this allows us to move work items between 'projects' without recreation as well as any template changes apply to all projects globally).  I would really like to see a team filter at the rule level just like with 'teamProjectColletion' and 'teamProject' (maybe just 'team'?) that would allow me to specify the team name and apply it to all of the handlers.

I won't be able to implement on our live TFS until this is in place, but I'm looking forward to finally having slack updates!  Thanks so much for working on this!

**Comment by gregpakes** [comment]
@shaneedwards This is already implemented on the Checkin Handler. The PR has been merged.

**Comment by shaneedwards** [comment]
@gregpakes that's awesome!  @kria it sounds like you offered to make it more global if greg implimented the checkin portion--do you have plans to do that in the near future?  I have this working in a test setup and it is awesome, I just can't put it to use with 20+ teams without scoping it down to specific channels either by area path or project team.

Thanks again,

Shane

**Comment by kria** [comment]
Yeah that was the plan, I just haven't gotten to it yet. I'll take a look at it over the weekend and see what I can do.

**Comment by shaneedwards** [comment]
That would be awesome!

**Comment by kria** [comment]
I added the team name filter to most events and an area path filter for work items event. Check out [version 1.11][0] and see if it works for your setup.

[0]:https://github.com/kria/TfsNotificationRelay/releases/tag/v1.11.0

**Comment by shaneedwards** [comment]
I just tested this update and it works incredibly well.  Scoping updates to the area path gives me all the flexibility I need!  I can't say thank you enough for putting this together.  I've been missing JIRA mainly due to the integration it provides and this clears most of it up.  I should have this in my production system later today--teams are going to love it!
